package ir.example.newstest

object Versions {
    const val kotlinVersion = "1.3.72"
    const val appCompatVersion = "1.1.0"
    const val constraintLayoutVersion = "1.1.3"
    const val fragmentKtxVersion = "1.2.0-alpha03"
    const val ktxVersion = "1.3.0"
    const val supportFragmentVersion = "1.0.0"
    const val kotlinGradlePluginVersion = "4.0.0"
    const val navigationVersion = "2.2.0-alpha03"
    const val roomVersion = "2.2.5"
    const val coroutineVersion = "1.3.0-M1"
    const val glideVersion = "4.9.0"
    const val lifecycleVersion = "2.2.0-alpha03"
    const val retrofitVersion = "2.6.0"
    const val okHttpVersion = "3.12.0"
    const val recyclerViewVersion = "1.1.0"
    const val googleMaterialVersion = "1.1.0-alpha10"
    const val multidexVersion = "1.0.3"
    const val koinVersion = "2.0.0-GA"
    const val junitVersion = "4.12"
    const val leakCanaryVersion = "2.0-beta-2"
    const val timberVersion = "4.7.1"
    const val testRunnerVersion = "1.1.1"
    const val espressoVersion = "3.2.0"
    const val daggerVersion = "2.25.4"
    const val rxJavaVersion = "2.2.16"
    const val rxAndroidVersion = "2.1.1"
    const val sdp = "1.0.6"



    const val lottieVersion = "3.2.2"
    const val permissionDispatcherVersion = "4.3.1"
    const val viewAnimatorVersion = "1.1.0"
    const val threeTenABPVersion = "1.2.0"
    const val firebaseVersion = "17.2.0"
    const val cloudMessagingVersion = "20.0.0"
    const val crashlyticVersion = "2.10.1"
    const val goldFingerVersion = "1.2.0"
    const val uCropVersion = "2.2.3"
    const val kBarcodeVersion = "1.0.4"
    const val emojiVersion = "28.0.0"
    const val persianDateVersion = "0.7"
    const val statusAlertVersion = "1.0.2"
    const val authApiVersion = "17.1.0"
    const val discreteScrollViewVersion = "1.4.9"
    const val overScrollVersion = "1.0.4"
    const val carouselViewVersion = "0.1.5"
    const val expansionpanelVersion = "2.0.7"
    const val numberPickerVersion = "2.4.8"
    const val qrGenVersion = "2.6.0"
    const val processPhoenixVersion = "2.0.0"
    const val rootBeerVersion = "0.0.7"
    const val swipyVersion = "1.2.3"
    const val prefsVersion = "1.1.0"
}